import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className="container mx-auto py-4 px-4 max-w-lg"
      >
        <Link href="/users/auth">Auth</Link>
        <Link href="/api/auth/logout">Logout</Link>
        {children}
      </body>
    </html>
  );
}
